const input = document.querySelector(".container > input");
const nama = document.getElementById("nama");
const khodam = document.getElementById("khodam");

// list khodam di-generate oleh ChatGPT
const listKhodam = [
  "Motor Keong",
  "Mobil Ayam",
  "Kereta Pisang",
  "Bus Durian",
  "Sepeda Naga",
  "Helikopter Kelinci",
  "Kapal Semangka",
  "Perahu Apel",
  "Traktor Sapi",
  "Becak Anggur",
  "Skuter Jeruk",
  "Truk Manggis",
  "Pesawat Kucing",
  "Kereta Labu",
  "Mobil Tomat",
  "Bus Kuda",
  "Sepeda Kura-kura",
  "Helikopter Melon",
  "Kapal Jeruk",
  "Perahu Nanas",
  "Traktor Bebek",
  "Becak Kambing",
  "Skuter Sosis",
  "Truk Kelapa",
  "Pesawat Lembu",
  "Kereta Mangga",
  "Mobil Kelinci",
  "Bus Monyet",
  "Sepeda Badak",
  "Helikopter Durian",
  "Kapal Strawberry",
  "Perahu Manggis",
  "Traktor Gajah",
  "Becak Elang",
  "Skuter Udang",
  "Truk Ayam",
  "Pesawat Ikan",
  "Kereta Jambu",
  "Mobil Salak",
  "Bus Apel",
  "Sepeda Unta",
  "Helikopter Kambing",
  "Kapal Kiwi",
  "Perahu Sapi",
  "Traktor Burung",
  "Becak Anjing",
  "Skuter Babi",
  "Truk Kelinci",
  "Pesawat Serigala",
  "Kereta Anggur",
  "Mobil Alpukat",
  "Bus Kuda Nil",
  "Sepeda Domba",
  "Helikopter Sapi",
  "Kapal Roti",
  "Perahu Kucing",
  "Traktor Tupai",
  "Becak Keju",
  "Skuter Kalkun",
  "Truk Bebek",
  "Pesawat Ubi",
  "Kereta Ceri",
  "Mobil Padi",
  "Bus Singkong",
  "Sepeda Jagung",
  "Helikopter Melon",
  "Kapal Pisang",
  "Perahu Keong",
  "Traktor Durian",
  "Becak Mangga",
  "Skuter Tomat",
  "Truk Semangka",
  "Pesawat Mangga",
  "Kereta Rambutan",
  "Mobil Cabai",
  "Bus Leci",
  "Sepeda Pepaya",
  "Helikopter Anggur",
  "Kapal Jeruk",
  "Perahu Lemon",
  "Traktor Cokelat",
  "Becak Pisang",
  "Skuter Durian",
  "Truk Kacang",
  "Pesawat Brokoli",
  "Kereta Wortel",
  "Mobil Ketimun",
  "Bus Kol",
  "Sepeda Bawang",
  "Helikopter Kacang",
  "Kapal Kentang",
  "Perahu Kubis",
  "Traktor Lobak",
  "Becak Bayam",
  "Skuter Terong",
  "Truk Sawi",
  "Pesawat Jahe",
  "Kereta Tempe",
  "Mobil Tahu",
  "Bus Miso",
  "Sepeda Sushi",
  "Helikopter Ramen",
  "Kapal Udon",
  "Perahu Soba",
  "Traktor Kimchi",
  "Becak Nasi",
  "Skuter Sop",
  "Truk Gulai",
  "Pesawat Soto",
  "Kereta Pecel",
  "Mobil Rendang",
  "Bus Sate",
  "Sepeda Bakso",
  "Helikopter Nugget",
  "Kapal Burger",
  "Perahu Pizza",
  "Traktor Hotdog",
  "Becak Sandwich",
  "Skuter Donat",
  "Truk Kue",
  "Pesawat Es Krim",
  "Kereta Puding",
  "Mobil Yogurt",
  "Bus Susu",
  "Sepeda Kopi",
  "Helikopter Teh",
  "Kapal Jus",
  "Perahu Lassi",
  "Traktor Smoothie",
  "Becak Cappuccino",
  "Skuter Latte",
  "Truk Espresso",
  "Pesawat Air Kelapa",
  "Kereta Lemonade",
  "Mobil Sirup",
  "Bus Soda",
  "Sepeda Anggur",
  "Helikopter Susu Kedelai",
  "Kapal Air Jeruk",
  "Perahu Jus Mangga",
  "Traktor Jus Apel",
  "Becak Smoothie Berry",
  "Skuter Jus Melon",
  "Truk Jus Semangka",
  "Pesawat Jus Kiwi",
  "Kereta Jus Nanas",
  "Mobil Jus Pisang",
  "Bus Jus Anggur",
  "Sepeda Jus Lemon",
  "Helikopter Jus Jambu",
  "Kapal Jus Sirsak",
  "Perahu Jus Belimbing",
  "Traktor Jus Markisa",
  "Becak Jus Pepaya",
  "Skuter Jus Rambutan",
  "Truk Jus Salak",
  "Pesawat Jus Leci",
  "Kereta Jus Kelapa",
  "Mobil Jus Mangga",
  "Bus Jus Alpukat",
  "Sepeda Jus Duku",
  "Helikopter Jus Naga",
  "Kapal Jus Anggur",
  "Perahu Jus Delima",
  "Traktor Jus Aprikot",
  "Becak Jus Persik",
  "Skuter Jus Pir",
  "Truk Jus Plum",
  "Pesawat Jus Buah Naga",
  "Kereta Jus Pisang",
  "Mobil Jus Jeruk",
  "Bus Jus Lemon",
  "Sepeda Jus Stroberi",
  "Helikopter Jus Kiwi",
  "Kapal Jus Melon",
  "Perahu Jus Semangka",
  "Traktor Jus Apel",
  "Becak Jus Anggur",
  "Skuter Jus Belimbing",
  "Truk Jus Sirsak",
  "Pesawat Jus Jambu",
  "Kereta Jus Nanas",
  "Mobil Jus Mangga",
  "Bus Jus Rambutan",
  "Sepeda Jus Salak",
  "Helikopter Jus Leci",
  "Kapal Jus Kelapa",
  "Perahu Jus Duku",
  "Traktor Jus Alpukat",
  "Becak Jus Markisa",
  "Skuter Jus Pepaya",
  "Truk Jus Delima",
  "Pesawat Jus Aprikot",
  "Kereta Jus Anggur",
  "Mobil Jus Naga",
  "Bus Jus Pisang",
  "Sepeda Jus Jeruk",
  "Helikopter Jus Lemon",
  "Kapal Jus Stroberi",
  "Perahu Jus Kiwi",
  "Traktor Jus Melon",
  "Becak Jus Semangka",
  "Skuter Jus Apel",
  "Truk Jus Anggur",
  "Pesawat Jus Sirsak",
  "Kereta Jus Belimbing",
  "Mobil Jus Jambu",
  "Bus Jus Nanas",
  "Sepeda Jus Mangga",
  "Helikopter Jus Rambutan",
  "Kapal Jus Salak",
  "Perahu Jus Leci",
  "Traktor Jus Kelapa",
  "Becak Jus Duku",
  "Skuter Jus Alpukat",
  "Truk Jus Markisa",
  "Pesawat Jus Pepaya",
  "Kereta Jus Delima",
  "Mobil Jus Aprikot",
  "Bus Jus Anggur",
  "Sepeda Jus Naga",
  "Helikopter Jus Pisang",
  "Kapal Jus Jeruk",
  "Perahu Jus Lemon",
  "Traktor Jus Stroberi",
  "Becak Jus Kiwi",
  "Skuter Jus Melon",
  "Truk Jus Semangka",
  "Pesawat Jus Apel",
  "Kereta Jus Anggur",
  "Mobil Jus Sirsak",
  "Bus Jus Belimbing",
  "Sepeda Jus Jambu",
  "Helikopter Jus Nanas",
  "Kapal Jus Mangga",
  "Perahu Jus Rambutan",
  "Traktor Jus Salak",
  "Becak Jus Leci",
  "Skuter Jus Kelapa",
  "Truk Jus Duku",
  "Pesawat Jus Alpukat",
  "Kereta Jus Markisa",
  "Mobil Jus Pepaya",
  "Bus Jus Delima",
  "Sepeda Jus Aprikot",
  "Helikopter Jus Anggur",
  "Kapal Jus Naga",
  "Perahu Jus Pisang",
  "Traktor Jus Jeruk",
  "Becak Jus Lemon",
  "Skuter Jus Stroberi",
  "Truk Jus Kiwi",
  "Pesawat Jus Melon",
  "Kereta Jus Semangka",
  "Mobil Jus Apel",
  "Bus Jus Anggur",
  "Sepeda Jus Sirsak",
  "Helikopter Jus Belimbing",
  "Kapal Jus Jambu",
  "Perahu Jus Nanas",
  "Traktor Jus Mangga",
  "Becak Jus Rambutan",
  "Skuter Jus Salak",
  "Truk Jus Leci",
  "Pesawat Jus Kelapa",
  "Kereta Jus Duku",
  "Mobil Jus Alpukat",
  "Bus Jus Markisa",
  "Sepeda Jus Pepaya",
  "Helikopter Jus Delima",
  "Kapal Jus Aprikot",
];

function randomPickKhodam() {
  const listLength = listKhodam.length;
  const randomIndex = Math.floor(Math.random() * listLength - 1);
  return listKhodam[randomIndex];
}

function handleClick() {
  nama.textContent = "Nama: " + input.value;
  khodam.textContent = input.value? "Jenis Khodam: " + randomPickKhodam(): "Jenis Khodam: ";
  input.value = "";
}
